spring:
  application:
    name: my-circuitbreaker-poc

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 999999s
        failureRateThreshold: 80

    instances:
      propertiesInstance:
        automaticTransitionFromOpenToHalfOpenEnabled: false
        registerHealthIndicator: true
        recordFailurePredicate: com.example.my_circuitbreaker_poc.exception.BussnessPredicate
        baseConfig: default
        waitDurationInOpenState: 5000

logging:
  level:
    root: INFO
    io.github.resilience4j.circuitbreaker: DEBUG