spring:
  application:
    name: my-circuitbreaker-poc

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 1
        maxWaitDurationInHalfOpenState: 999999s
        waitDurationInOpenState: 999999s
        failureRateThreshold: 80

    instances:
      propertiesInstance:
        automaticTransitionFromOpenToHalfOpenEnabled: false
        registerHealthIndicator: true
        recordFailurePredicate: com.example.my_circuitbreaker_poc.exception.BussnessPredicate
        baseConfig: default

logging:
  level:
    root: INFO
    io.github.resilience4j.circuitbreaker: DEBUG